# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('size', models.CharField(choices=[(b'A', b'Less than 50 full-time employees'), (b'B', b'Between 50-100 full-time employees'), (b'C', b'Greater than 100 full-time employees')], default=b'?', max_length=1)),
                ('budget', models.CharField(choices=[(b'A', b'Less than $10'), (b'B', b'Less than $100'), (b'C', b'Less than $500')], default=b'?', max_length=1)),
                ('pageviews', models.CharField(choices=[(b'A', b'Less than 10,000'), (b'B', b'Less than 50,000'), (b'C', b'Less than 1 million'), (b'D', b'More than 1 million')], default=b'?', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oneliner.Organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
