# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneliner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(blank=True, max_length=3000, null=True)),
                ('performance', models.CharField(blank=True, max_length=3000, null=True)),
                ('privacy', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='budget',
            field=models.CharField(choices=[(b'A', b'Less than $10'), (b'B', b'Less than $100'), (b'C', b'Less than $500'), (b'D', b'More than $500')], default=b'?', max_length=1),
        ),
        migrations.AddField(
            model_name='services',
            name='organizations',
            field=models.ManyToManyField(blank=True, null=True, to='oneliner.Organization'),
        ),
    ]
